name: frontend

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  

      - name: Install dependencies
        run: |
          npm install --save-dev jest@latest @testing-library/react@latest
          npm ci

      - name: Run tests
        run: npx jest --coverage /tests
